runtime: python311

entrypoint: gunicorn -b :$PORT app_on_the_go:app --workers=4 --timeout=300

env_variables:
  OPENAI_API_KEY: "your_openai_key_here"
  ANTHROPIC_API_KEY: "your_anthropic_key_here"
  FLASK_ENV: "production"

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.6
